language: node_js

node_js:
  - "node"

env:
  global:
    - HUGO_VERSION=0.19

before_install:
  - wget https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xvzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mkdir -p $HOME/bin
  - cp hugo_${HUGO_VERSION}_linux_amd64/hugo_${HUGO_VERSION}_linux_amd64 $HOME/bin/hugo

install:
  - npm install -qg bower grunt-cli
  - git config --global user.email "${GIT_EMAIL}"
  - git config --global user.name "${GIT_NAME}"

script:
  - cd themes
  - git clone https://github.com/wet-boew/wet-boew-hugo.git wxt
  - cd wxt && bower install && cd ../..
  - ./deploy.sh "Initial commit" > /dev/null 2>&1
